### ISSUE TITLE
Can we please get an update for 10.15.7?

### ISSUE THREAD

**Issue by ShroomKing** [fabioiop/ImprovementUI#3]
I manually installed 10.15.6 files and it no longer boots so I guess an update is needed.

I can post the binaries so you can take a look in case you don't have 10.15.7

**Comment by fabioiop** [comment]
I'll release the right files in a couple days

**Comment by ShroomKing** [comment]
ok, thank you!

**Comment by teemue** [comment]
Any progress?

**Comment by ShroomKing** [comment]
Files for 15.7 have been posted in releases https://github.com/fabioiop/ImprovementUI/releases
