### ISSUE TITLE
How ImprovementUI works

### ISSUE THREAD

**Issue by minh-ton** [fabioiop/ImprovementUI#4]
Hi there! 

Thanks for your great work of making non-Metal Macs to look like the supported ones.

I'm really curious about how this works, especially what you've modified in AppKit
and HIToolBox for the cosmetic improvements. 

Would it be possible to explain in a little bit more detail on how this works? I'd really appreciate it, thank you!

**Comment by fabioiop** [comment]
Returning false, or NOP, in some calls that were translated to Metal when generating the window mask. 
And: [https://forums.macrumors.com/threads/macos-10-15-catalina-on-unsupported-macs.2183772/page-258?post=27941867#post-27941841](https://forums.macrumors.com/threads/macos-10-15-catalina-on-unsupported-macs.2183772/page-258?post=27941867#post-27941841)
